### M2 SID 2026-2027
<div align="center">
  <h2 style="font-size: 36px;"><b>TP n°1 : web scraping</b></h2>
</div>

 
<div align="center">
  <h2 style="font-size: 30px;"><b>Par Muriel Visani</b></h2>
</div>

## Partie I: en autonomie

#### Lire le site suivant, pour mieux comprendre la manière dont BeautifulSoup fonctionne : https://cloro.dev/blog/beautifulsoup-web-scraping/

#### Faire le tutoriel suivant, qui vous permettra de découvrir la libraire BeautifulSoup de Python 
https://tech-insider.org/fr/tutoriel-web-scraping-python-extraction-donnees-2026/

In [1]:
!pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

[notice] A new release of pip available: 22.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Partie II: Web scraping - événements musicaux au CEPAC Silo, à Marseille

#### L'objet de cette partie est de vous faire :

> #### - Récupérer les données relatives aux événements culturels au CEPAC Silo à Marseille (concerts + différents spectacles : humour, danse, etc.). Le lien de cette page est "https://www.cepacsilo-marseille.fr/evenements/"

> #### - Structurer ces données

> #### - Placer ces données dans un dataframe Pandas et mener une analyse exploratoire sommaire des données, c.à.d. calculer quelques statistiques de base sur ces événements (prix moyen, etc.)

Parfois, dans ce TP, je vous donne la réponse attendue, selon le contenu de la page lorsque j'ai monté ce TP (lors de l'été 2026).

Le cas échéant, si la page du CEPAC a trop changé depuis que j'ai monté ce TP, alors je vous donne son contenu dans le répertoire cepac_silo_pages.zip.

Vous pouvez travailler sur ce répertoire zippé pour vérifier que vous avez bien la bonne réponse.

#### Q0
Importez les librairies nécessaires

In [2]:
import requests
import os
import httpx
import csv
import pandas as pd
from bs4 import BeautifulSoup

#### Q1 
Avec les outils de développement de Chrome (et le cas échéant un éditeur de code), regardez bien attentivement le code HTM de la page "https://www.cepacsilo-marseille.fr/evenements/", testez les liens URL qui s'y trouvent, etc. C'est une étape cruciale.

Il s'agit que vous compreniez comment est structurée la page, où se trouvent les données importantes, etc.

Dans ce TP, on va s'intéresser aux informations concernant les événements musicaux d'Aix-Marseille, à savoir :

> - le type d'événement (concert, spectacle, one man show, humour, etc.)

> - la date de l'événement : nom du jour (lundi, mardi, etc), numéro du jour (01 comme dans 1er Octobre par exemple), le nom du mois, l'année

> - l'heure de l'événement 

> - l'artiste, ou la liste des artistes, qui se produira sur scène

> - le prix d'une place, soit en catégorie 2, soit en catégorie unique, soit en catégorie debout (pour cela, il faut normalement cliquer sur "Réserver")

Tentez de repérer, dans cette page HTML, où se trouvent ces informations, et donnez quelques éléments de réponse (balises où ces événement se trouvent) dans la cellule Markdown ci-après.

Dans cette page les informations sont entre différentes balises à savoir pour :

Type événement : une balise span
date d'événement : une balise p
l'artiste :h3
pour l'heure une fois que l'on clique sur l'évenement on le retrouve dans une balise span
et enfin pour le prix on doit chercher dans la classe category price ou on va trouver les prix entre des balises div

#### Q2
Avec httpx, récupérez automatiquement le nombre de pages de "https://www.cepacsilo-marseille.fr/evenements/" (normalement 10 en tout). 

Repérez les URLs de ces pages, et ce qui s'affiche quand vous allez une page trop loin.

In [3]:


url = "https://www.cepacsilo-marseille.fr/evenements/"

response = httpx.get(url)
response.raise_for_status() # to ensure we got a successful response

soup = BeautifulSoup(response.text, "lxml")

pages = soup.find_all(
    "a",
    class_="events-archive__pagination-item"
)

numeros_pages = []

for page in pages:
    numero = page.get("data-page")

    numeros_pages.append(int(numero))

nombre_pages = max(numeros_pages)
print("Nombre de pages :", nombre_pages)

Nombre de pages : 10

#### Q3
Avec httpx, récupérez tout le contenu textuel de toutes les pages de "https://www.cepacsilo-marseille.fr/evenements/", et mettez-le dans une liste appelée "pages".
Vérifiez que les status_code commencent bien par 2 (ce qui signifie que les pages ont bien été scrapées).

In [4]:
pages = []

for numero in range(1, nombre_pages + 1):

    url = f"https://www.cepacsilo-marseille.fr/evenements/page/{numero}/"

    response = httpx.get(url, follow_redirects=True)

    print(f"Page {numero} : {response.status_code}")

    if str(response.status_code).startswith("2"):
        pages.append(response.text)

Page 1 : 200
Page 2 : 200
Page 3 : 200
Page 4 : 200
Page 5 : 200
Page 6 : 200
Page 7 : 200
Page 8 : 200
Page 9 : 200
Page 10 : 200

#### Q4

Toujours avec httpx, sauvergardez le contenu HTML de l'ensemble des pages d'événements (un fichier HTML par page), dans un répertoire nommé "TP_cepac_silo_pages".

In [5]:



os.makedirs("TP_cepac_silo_pages", exist_ok=True)


for i in range(len(pages)):

    num_page = f"TP_cepac_silo_pages/page_{i + 1}.html"

    with open(num_page, "w", encoding="utf-8") as fichier:
        fichier.write(pages[i])

#### Q5
Avec BeautifulSoup, placez le contenu HTML de "pages" (toutes les pages HTML) dans une liste appelée "soup".

In [6]:


soup = []

for page in pages:
    contenu = BeautifulSoup(page, "lxml")
    soup.append(contenu)

#print(soup)

#### Q6
Retournez (avec print) le titre du premier événement mentionné dans la première page. Le type de sortie attendue est par exemple :

Alizée

In [7]:
titre = soup[0].find_all("h3", class_="card-event__title")

print(titre[0].text)

DEVIN TOWNSEND

#### Q7
## <font color='red'> Point de validation 1 : une fois que vous aurez terminé cette question, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 

Pour tous les événements mentionnés dans la première page, retournez (avec print) le titre de cet événement, précédé du mot-clé "Événement" et de l'ordre d'apparition de cet événement dans la page (exemple "Événement 1"). Le type de sortie attendue est par exemple :

Événement 1: Alizée

Événement 2: MAC DEMARCO

Événement 3: DEVIN TOWNSEND

Événement 4: The bootleg beatles

Événement 5: LAURENT FEBVAY

Événement 6: LETZ ZEP

Événement 7: THE SISTERS OF MERCY

Événement 8: ORCHESTRE CURIEUX

Événement 9: BREL !

Événement 10: Marie Benoliel

Événement 11: TIF

In [8]:
titres =[]
for s in soup:
  titre = s.find_all("h3", class_="card-event__title")
  titres.append(titre)

# print all titles of first page
page_1_titles = [t.text for t in titres[0]]
print(page_1_titles)

['DEVIN TOWNSEND', 'The bootleg beatles', 'LAURENT FEBVAY', 'LETZ ZEP', 'THE SISTERS OF MERCY', 'BREL !', 'Marie Benoliel', 'TIF', 'Boudchart', 'WORLDS APART', 'Amine Radi']

#### Q8
Pour tous les événements mentionnés dans la première page, précisez le type d'événement (Concert, one man show, humour, etc). Le type de sortie attendue est par exemple :

```Événement 1 : Alizée  -  Concert
Événement 2 : MAC DEMARCO  -  Concert
Événement 3 : DEVIN TOWNSEND  -  Concert
Événement 4 : The bootleg beatles  -  Concert
Événement 5 : LAURENT FEBVAY  -  One man show
Événement 6 : LETZ ZEP  -  Concert
Événement 7 : THE SISTERS OF MERCY  -  Concert
Événement 8 : ORCHESTRE CURIEUX  -  Spectacle
Événement 9 : BREL !  -  Spectacle
Événement 10 : Marie Benoliel  -  Spectacle
Événement 11 : TIF  -  Concert - Rap / Urbain

In [9]:
# type of event is inside span class="tag-pill"
types = []
for s in soup:
  type_event = s.find_all("span", class_="tag-pill")
  types.append(type_event)

# print all types of events of first page with respective titles
page_1_types = [t.text for t in types[0]]
page_1_titles = [t.text for t in titres[0]]
for i in range(len(page_1_titles)):
    print(f"Événement {i+1}: {page_1_titles[i]} - Type: {page_1_types[i]}")

Événement 1: DEVIN TOWNSEND - Type: Concert
Événement 2: The bootleg beatles - Type: Concert
Événement 3: LAURENT FEBVAY - Type: One man show
Événement 4: LETZ ZEP - Type: Concert
Événement 5: THE SISTERS OF MERCY - Type: Concert
Événement 6: BREL ! - Type: Spectacle
Événement 7: Marie Benoliel - Type: Spectacle
Événement 8: TIF - Type: Concert - Rap / Urbain
Événement 9: Boudchart - Type: Concert
Événement 10: WORLDS APART - Type: Concert
Événement 11: Amine Radi - Type: Humour

#### Q9
Pour tous les événements mentionnés dans la première page, précisez la ou les date(s) de l'événement, comme par exemple :

```Événement 1 : Alizée  -  Concert
   Le  Jeudi 10 septembre 2026 - 20:00
Événement 2 : MAC DEMARCO  -  Concert
   Le  Dimanche 13 septembre 2026 - 20:00
   Le  Lundi 14 septembre 2026 - 20:00
Événement 3 : DEVIN TOWNSEND  -  Concert
   Le  Mercredi 23 septembre 2026 - 20:00
Événement 4 : The bootleg beatles  -  Concert
   Le  Jeudi 24 septembre 2026 - 20:00
Événement 5 : LAURENT FEBVAY  -  One man show
   Le  Samedi 26 septembre 2026 - 20:30
Événement 6 : LETZ ZEP  -  Concert
   Le  Mercredi 30 septembre 2026 - 20:00
Événement 7 : THE SISTERS OF MERCY  -  Concert
   Le  Jeudi 01 octobre 2026 - 20:00
Événement 8 : ORCHESTRE CURIEUX  -  Spectacle
   Le  Vendredi 02 octobre 2026 - 20:00
Événement 9 : BREL !  -  Spectacle
   Le  Dimanche 04 octobre 2026 - 17:00
Événement 10 : Marie Benoliel  -  Spectacle
   Le  Mercredi 07 octobre 2026 - 20:00
Événement 11 : TIF  -  Concert - Rap / Urbain
   Le  Jeudi 08 octobre 2026 - 20:00```

In [10]:
evenements = soup[0].find_all(class_="card-event")

compteur = 1

for evenement in evenements:

    titre = evenement.find("h3", class_="card-event__title")
    type_event = evenement.find("span", class_="tag-pill")
    date = evenement.find("p", class_="card-event__date")

    print(f"Événement {compteur}: {titre.text} - {type_event.text}")
    print(f"   Le {date.text}")

    compteur = compteur + 1

Événement 1: DEVIN TOWNSEND - Concert
   Le Mercredi 23 septembre 2026
Événement 2: The bootleg beatles - Concert
   Le Jeudi 24 septembre 2026
Événement 3: LAURENT FEBVAY - One man show
   Le Samedi 26 septembre 2026
Événement 4: LETZ ZEP - Concert
   Le Mercredi 30 septembre 2026
Événement 5: THE SISTERS OF MERCY - Concert
   Le Jeudi 1 octobre 2026
Événement 6: BREL ! - Spectacle
   Le Dimanche 4 octobre 2026
Événement 7: Marie Benoliel - Spectacle
   Le Mercredi 7 octobre 2026
Événement 8: TIF - Concert - Rap / Urbain
   Le Jeudi 8 octobre 2026
Événement 9: Boudchart - Concert
   Le Vendredi 9 octobre 2026
Événement 10: WORLDS APART - Concert
   Le Samedi 10 octobre 2026
Événement 11: Amine Radi - Humour
   Le Samedi 17 octobre 2026

#### Q10
Même question, mais pour tous les CONCERTS mentionnés dans la page (mais pas pour les autres événements).

Le type de sortie attendue est par exemple :

```Événement 1 : Alizée  -  Concert
   Le  Jeudi 10 septembre 2026 - 20:00
Événement 2 : MAC DEMARCO  -  Concert
   Le  Dimanche 13 septembre 2026 - 20:00
   Le  Lundi 14 septembre 2026 - 20:00
Événement 3 : DEVIN TOWNSEND  -  Concert
   Le  Mercredi 23 septembre 2026 - 20:00
Événement 4 : The bootleg beatles  -  Concert
   Le  Jeudi 24 septembre 2026 - 20:00
Événement 5 : LETZ ZEP  -  Concert
   Le  Mercredi 30 septembre 2026 - 20:00
Événement 6 : THE SISTERS OF MERCY  -  Concert
   Le  Jeudi 01 octobre 2026 - 20:00
Événement 7 : TIF  -  Concert - Rap / Urbain
   Le  Jeudi 08 octobre 2026 - 20:00```

In [11]:


compteur = 1

for evenement in evenements:

    type_event = evenement.find(class_="tag-pill")

    if "Concert" in type_event.text:

        titre = evenement.find("h3", class_="card-event__title")
        date = evenement.find("p", class_="card-event__date")

        print(f"Événement {compteur}: {titre.text} - Concert")
        print(f"   Le {date.text}")

        compteur = compteur + 1

Événement 1: DEVIN TOWNSEND - Concert
   Le Mercredi 23 septembre 2026
Événement 2: The bootleg beatles - Concert
   Le Jeudi 24 septembre 2026
Événement 3: LETZ ZEP - Concert
   Le Mercredi 30 septembre 2026
Événement 4: THE SISTERS OF MERCY - Concert
   Le Jeudi 1 octobre 2026
Événement 5: TIF - Concert
   Le Jeudi 8 octobre 2026
Événement 6: Boudchart - Concert
   Le Vendredi 9 octobre 2026
Événement 7: WORLDS APART - Concert
   Le Samedi 10 octobre 2026

#### Q11

## <font color='red'> Point de validation 2 : une fois que vous aurez terminé cette question, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 

Même question, mais pour tous les EVENEMENTS mentionnés dans TOUTES LES pages.

Conseil : mettre les événements dans une liste Python, et utiliser une boucle pour "parser" chacun de ces événements un à un, en n'oubliant pas de mettre à None les éventuels éléments vides. Cela vous facilitera considérablement le travail pour les questions suivantes !


La sortie attendue devra mentionner tous les éléments ci-dessous et respecter la même mise en forme :

```Événement 1 : Alizée  -  Concert
   Le  Jeudi 10 septembre 2026 - 20:00
Événement 2 : MAC DEMARCO  -  Concert
   Le  Dimanche 13 septembre 2026 - 20:00
   Le  Lundi 14 septembre 2026 - 20:00
Événement 3 : DEVIN TOWNSEND  -  Concert
   Le  Mercredi 23 septembre 2026 - 20:00
Événement 4 : The bootleg beatles  -  Concert
   Le  Jeudi 24 septembre 2026 - 20:00
Événement 5 : LAURENT FEBVAY  -  One man show
   Le  Samedi 26 septembre 2026 - 20:30
Événement 6 : LETZ ZEP  -  Concert
   Le  Mercredi 30 septembre 2026 - 20:00
Événement 7 : THE SISTERS OF MERCY  -  Concert
   Le  Jeudi 01 octobre 2026 - 20:00
Événement 8 : ORCHESTRE CURIEUX  -  Spectacle
   Le  Vendredi 02 octobre 2026 - 20:00
Événement 9 : BREL !  -  Spectacle
   Le  Dimanche 04 octobre 2026 - 17:00
Événement 10 : Marie Benoliel  -  Spectacle
   Le  Mercredi 07 octobre 2026 - 20:00
Événement 11 : TIF  -  Concert - Rap / Urbain
   Le  Jeudi 08 octobre 2026 - 20:00
Événement 12 : WORLDS APART  -  Concert
   Le  Samedi 10 octobre 2026 - 20:00
Événement 13 : Amine Radi  -  Humour
   Le  Samedi 17 octobre 2026 - 20:30
Événement 14 : TINA ARENA  -  Concert
   Le  Mercredi 21 octobre 2026 - 20:00
Événement 15 : THE VOICE OF GEORGE MICHAEL  -  Concert
   Le  Jeudi 22 octobre 2026 - 20:30
   
...

Événement 98 : NASH  -  Humour
   Le  Vendredi 05 novembre 2027 - 20:30
Événement 99 : ARNAUD TSAMERE  -  Humour
   Le  Samedi 20 novembre 2027 - 20:00
Événement 100 : JULIEN ROSSIER EST COLUCHE !  -  Spectacle
   Le  Jeudi 25 novembre 2027 - 20:00
Événement 101 : SOFIA BELABBES  -  Humour
   Le  Vendredi 10 décembre 2027 - 20:00
Événement 102 : LES DIX COMMANDEMENTS  -  Spectacle
   Le  Jeudi 24 février 2028 - 20:30
Événement 103 : PIAF ! LE SPECTACLE  -  Spectacle
   Le  Mardi 29 février 2028 - 20:30

In [12]:
evenements = []

for page in soup:
    evenements_page = page.find_all(class_="card-event")

    for evenement in evenements_page:
        evenements.append(evenement)
#jusqu'ici j'ai recupéré les evenements de toutes les pages que javais dans soup que j'ai mtn dans evenement


compteur = 1

for evenement in evenements:

    titre = evenement.find("h3", class_="card-event__title")
    types = evenement.find_all("span", class_="tag-pill")

    lien = evenement.find("a", class_="card-event__overlay-link") # here we are looking for the link to the event's detail page

    if lien is None:
        url_evenement = None
    else:
        url_evenement = lien.get("href")


    print(f"Événement {compteur} : {titre.text}", end="")

    for type_event in types:
        print(f" - {type_event.text}", end="")

    print()

    if url_evenement is not None:

        response = httpx.get(url_evenement)

        soup_evenement = BeautifulSoup(response.text, "lxml")

        sessions = soup_evenement.find_all("li", class_="bl-he__session")


        for session in sessions:

            date = session.find("span", class_="bl-he__session-date")
            heure = session.find("span", class_="bl-he__session-time")

            if date is None:
                date_texte = None
            else:
                date_texte = date.text

            if heure is None:
                heure_texte = None
            else:
                heure_texte = heure.text

            if date_texte is not None and heure_texte is not None:
                print(f"   Le {date_texte} - {heure_texte}")

    compteur = compteur + 1

Événement 1 : DEVIN TOWNSEND - Concert
   Le mercredi 23 septembre 2026 - 20h00
Événement 2 : The bootleg beatles - Concert
Événement 3 : LAURENT FEBVAY - One man show
   Le samedi 26 septembre 2026 - 20h30
Événement 4 : LETZ ZEP - Concert
   Le mercredi 30 septembre 2026 - 20h00
Événement 5 : THE SISTERS OF MERCY - Concert
   Le jeudi 01 octobre 2026 - 20h00
Événement 6 : BREL ! - Spectacle
   Le dimanche 04 octobre 2026 - 17h00
Événement 7 : Marie Benoliel - Spectacle
   Le mercredi 07 octobre 2026 - 20h00
Événement 8 : TIF - Concert - Rap / Urbain
   Le jeudi 08 octobre 2026 - 20h00
Événement 9 : Boudchart - Concert
   Le vendredi 09 octobre 2026 - 20h00
Événement 10 : WORLDS APART - Concert
   Le samedi 10 octobre 2026 - 20h00
Événement 11 : Amine Radi - Humour
   Le samedi 17 octobre 2026 - 20h30
Événement 12 : TINA ARENA - Concert
   Le mercredi 21 octobre 2026 - 20h00
Événement 13 : THE VOICE OF GEORGE MICHAEL - Concert
   Le jeudi 12 février 2026 - 20h30
   Le jeudi 22 octobre 2026 - 20h30
Événement 14 : Naïm - Humour
   Le samedi 24 octobre 2026 - 20h00
   Le samedi 20 mars 2027 - 20h00
Événement 15 : Samuel Bambi - Humour
   Le jeudi 29 octobre 2026 - 20h00
Événement 16 : Bachar Mar-Khalifé joue Christophe - Concert
   Le vendredi 30 octobre 2026 - 21h00
Événement 17 : Belinda Davids - Concert
   Le mercredi 04 novembre 2026 - 20h00
Événement 18 : THE 5 ROSIES – TRIBUTE TO AC/DC - Concert
   Le jeudi 05 novembre 2026 - 20h00
Événement 19 : NACIM HADDAD - Concert
   Le samedi 07 novembre 2026 - 20h00
Événement 20 : Hubert-Félix Thiéfaine - Concert
   Le dimanche 08 novembre 2026 - 18h00
   Le samedi 06 mars 2027 - 20h00
Événement 21 : SECRET(S) MEDICAL - Théâtre
   Le jeudi 12 novembre 2026 - 20h00
Événement 22 : SO LA LUNE - Concert - Rap / Urbain
   Le vendredi 13 novembre 2026 - 20h00
Événement 23 : DRAG RACE FRANCE LIVE - Comédie musicale
   Le samedi 14 novembre 2026 - 20h00
Événement 24 : MARY CANDIES - Jeune Public
   Le dimanche 15 novembre 2026 - 15h00
Événement 25 : Tutu - Danse
   Le jeudi 19 novembre 2026 - 20h00
Événement 26 : Danse avec les stars - Danse
   Le vendredi 20 novembre 2026 - 20h00
Événement 27 : Kad Merad & Michèle Laroque - Humour
   Le samedi 21 novembre 2026 - 20h00
Événement 28 : SPIDER-MAN - Spectacle
   Le dimanche 22 novembre 2026 - 17h00
Événement 29 : LAURENT VOULZY - Concert
   Le mercredi 25 novembre 2026 - 20h30
Événement 30 : Souad Massi - Concert
   Le jeudi 26 novembre 2026 - 20h30
Événement 31 : TITOFF - One man show
   Le samedi 28 novembre 2026 - 20h30
Événement 32 : CASSE-NOISETTE – BRITISH FESTIVAL BALLET - Ballet
   Le dimanche 29 novembre 2026 - 13h30
   Le dimanche 29 novembre 2026 - 17h30
Événement 33 : Jamel Comedy Club - Humour
   Le mercredi 02 décembre 2026 - 20h00
Événement 34 : MADAME ARTHUR ENSORCELLE DISNEY - Spectacle
   Le jeudi 03 décembre 2026 - 20h00
Événement 35 : Ronja  – Vincent Peirani - Jeune Public
   Le vendredi 04 décembre 2026 - 20h00
Événement 36 : Lynda Lemay et Jean-Felix Lalanne - Concert
   Le mardi 08 décembre 2026 - 20h00
Événement 37 : LALOU - Humour
   Le mercredi 09 décembre 2026 - 20h00
Événement 38 : DAVID CASTELLO-LOPES - Humour
   Le jeudi 10 décembre 2026 - 20h30
Événement 39 : PIETRAGALLA BARBARA - Danse
   Le vendredi 11 décembre 2026 - 20h30
Événement 40 : Légendes Arabes - Spectacle
   Le samedi 12 décembre 2026 - 20h00
Événement 41 : UN SOIR AVEC PIERRE ARDITI - Théâtre
   Le lundi 14 décembre 2026 - 20h00
Événement 42 : HIBA TAWAJI INVITE IBRAHIM MAALOUF - Concert
   Le mardi 15 décembre 2026 - 20h00
Événement 43 : Benjamin Biolay - Concert
   Le mercredi 16 décembre 2026 - 20h00
Événement 44 : Laurent Gerra - Humour
   Le samedi 19 décembre 2026 - 20h00
Événement 45 : LE LAC DES CYGNES – IMPERIAL HERITAGE BALLET - Ballet
   Le lundi 04 janvier 2027 - 20h00
Événement 46 : Verino - Humour
   Le vendredi 08 janvier 2027 - 20h00
Événement 47 : MARIZA - Concert
   Le samedi 09 janvier 2027 - 20h00
Événement 48 : LA RUE KETANOU - Concert
   Le mercredi 13 janvier 2027 - 20h30
Événement 49 : Sellig - Humour
   Le jeudi 14 janvier 2027 - 20h30
Événement 50 : Anne Tuffigo - Spectacle
   Le samedi 16 janvier 2027 - 20h00
Événement 51 : LES QUATRE SAISONS - Ballet
   Le vendredi 22 janvier 2027 - 20h00
Événement 52 : ILYES DJADEL - Humour
   Le samedi 23 janvier 2027 - 20h00
Événement 53 : MANO FAIT SON SHOW - Spectacle
   Le mercredi 27 janvier 2027 - 20h00
Événement 54 : Edgar-Yves - Humour
   Le jeudi 28 janvier 2027 - 20h00
Événement 55 : MOGUIZ - Humour
   Le samedi 30 janvier 2027 - 20h00
Événement 56 : JEREMY HABABOU - Concert
   Le dimanche 31 janvier 2027 - 17h00
Événement 57 : Tom baldetti - Humour
   Le mercredi 03 février 2027 - 20h30
Événement 58 : HAROUN - One man show
   Le samedi 06 février 2027 - 18h00
   Le samedi 06 février 2027 - 21h00
Événement 59 : Le Paname Comedy Club - Humour
   Le mardi 09 février 2027 - 20h30
   Le vendredi 12 février 2027 - 20h30
Événement 60 : LES FO’PLAFONDS - Spectacle
   Le jeudi 15 janvier 2026 - 20h30
   Le mercredi 10 février 2027 - 20h30
Événement 61 : ROLAND MAGDANE - Humour
   Le dimanche 14 février 2027 - 16h00
Événement 62 : La belle au bois dormant – IMPERIAL HERITAGE BALLET - Danse
   Le mercredi 17 février 2027 - 20h00
Événement 63 : LA LETTRE - Théâtre
   Le vendredi 19 février 2027 - 20h00
   Le samedi 20 février 2027 - 20h00
Événement 64 : Akim Omiri - Humour
   Le jeudi 25 février 2027 - 20h30
Événement 65 : DANY BOON - Humour
   Le vendredi 26 février 2027 - 20h00
Événement 66 : Pomme - Concert
   Le samedi 27 février 2027 - 20h00
Événement 67 : Thylacine - Concert
   Le jeudi 04 mars 2027 - 20h00
Événement 68 : PABLO MIRA - Humour
   Le vendredi 05 mars 2027 - 20h00
Événement 69 : MASK SINGER - Spectacle
   Le dimanche 07 mars 2027 - 17h30
Événement 70 : DON QUICHOTTE - Danse
   Le mercredi 10 mars 2027 - 20h00
Événement 71 : Tristan Lopin - Humour
   Le jeudi 11 mars 2027 - 20h30
Événement 72 : The world of Queen - Concert
   Le vendredi 12 mars 2027 - 20h30
Événement 73 : Izia - Concert
   Le samedi 13 mars 2027 - 20h00
Événement 74 : MARGUERITE - Concert
   Le mardi 16 mars 2027 - 20h00
Événement 75 : The U2 Experience - Concert
   Le mercredi 17 mars 2027 - 20h00
Événement 76 : ABBA GOLD – The concert show - Concert
   Le jeudi 18 mars 2027 - 20h00
Événement 77 : RODRIGUE - Humour
   Le vendredi 19 mars 2027 - 20h00
Événement 78 : Celtic Legends - Spectacle
   Le dimanche 21 mars 2027 - 14h30
   Le dimanche 21 mars 2027 - 17h30
Événement 79 : Olivier de Benoist - Humour
   Le mardi 23 mars 2027 - 20h30
Événement 80 : PIERRE DE MAERE - Concert
   Le mercredi 24 mars 2027 - 20h00
Événement 81 : Sniper - Concert - Rap / Urbain
   Le jeudi 25 mars 2027 - 20h30
Événement 82 : AMBRE - Concert
   Le vendredi 26 mars 2027 - 20h00
Événement 83 : Victoria Dauberville - Danse
   Le samedi 27 mars 2027 - 20h00
Événement 84 : Sheryfa Luna - Concert
   Le dimanche 28 mars 2027 - 17h00
Événement 85 : RODRIGO Y GABRIELA - Concert
   Le jeudi 01 avril 2027 - 20h00
Événement 86 : Camille - Concert
   Le vendredi 02 avril 2027 - 20h00
Événement 87 : SYLVIE VARTAN - Spectacle
   Le samedi 03 avril 2027 - 20h00
Événement 88 : Yanns - Concert
   Le dimanche 04 avril 2027 - 18h00
Événement 89 : CAR/MEN - Danse
   Le jeudi 08 avril 2027 - 20h00
Événement 90 : PHILIPPE CAVERIVIERE - Humour
   Le samedi 10 avril 2027 - 20h30
Événement 91 : LE LAC DES CYGNES – INTERNATIONAL FESTIVAL BALLET - Ballet
   Le dimanche 11 avril 2027 - 16h00
Événement 92 : The Muse Experience - Concert
   Le jeudi 15 avril 2027 - 20h30
Événement 93 : PIERRE EMMANUEL BARRé & AYMERIC LOMPRET - Humour
   Le mercredi 28 avril 2027 - 20h00
   Le jeudi 29 avril 2027 - 20h00
   Le vendredi 30 avril 2027 - 20h00
Événement 94 : NIGHT FEVER : A TRIBUTE TO THE BEE GEES - Concert
   Le jeudi 20 mai 2027 - 20h00
Événement 95 : Gilbert Montagné - Concert
   Le samedi 22 mai 2027 - 20h00
Événement 96 : Hervé Vilard - Concert
   Le dimanche 23 mai 2027 - 17h00
Événement 97 : CENDRILLON – BALLET JULIEN LESTEL - Ballet
   Le mercredi 26 mai 2027 - 20h00
Événement 98 : LA SALIDA DE RUBEN MOLINA - Danse
   Le jeudi 27 mai 2027 - 20h30
Événement 99 : EDOUARD DELOIGNON - Humour
   Le samedi 05 juin 2027 - 20h30
Événement 100 : COVERTRAMP, HOMMAGE A SUPERTRAMP - Concert
   Le samedi 02 octobre 2027 - 20h00
Événement 101 : Ycare - Concert
   Le vendredi 15 octobre 2027 - 20h00
Événement 102 : NASH - Humour
   Le vendredi 05 novembre 2027 - 20h30
Événement 103 : ARNAUD TSAMERE - Humour
   Le samedi 20 novembre 2027 - 20h00
Événement 104 : JULIEN ROSSIER EST COLUCHE ! - Spectacle
   Le jeudi 25 novembre 2027 - 20h00
Événement 105 : FORMIDABLE ! AZNAVOUR - Spectacle
   Le mercredi 01 décembre 2027 - 20h00
Événement 106 : BLANDINE LEHOUT - Humour
   Le vendredi 03 décembre 2027 - 20h00
Événement 107 : SOFIA BELABBES - Humour
   Le vendredi 10 décembre 2027 - 20h00
Événement 108 : LES DIX COMMANDEMENTS - Spectacle
   Le jeudi 24 février 2028 - 20h30
Événement 109 : YANN MARGUET - Humour
   Le samedi 26 février 2028 - 20h00
Événement 110 : PIAF ! LE SPECTACLE - Spectacle
   Le mardi 29 février 2028 - 20h30

### Q12

## <font color='red'> Point de validation 3 : une fois que vous aurez terminé cette question, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 


Pour chaque événement, rajouter le lien de réservation : celui où on peut trouver le prix des types de places que l'on veut (debout, catégorie 2 ou catégorie unique). Lorsque ce lien n'est pas donné (par exemple parce que le concert est complet), imprimer "Réservation impossible".

Mettre toutes ces informations (titre, catégorie, dates / heures, liens de réservation ou "Réservation impossible") dans un même dictionnaire de données. Cela vous facilitera beaucoup la tâche pour la suite...
    
N.B. Vous pourriez aussi mettre cela dans une liste, ça serait peut-être même plus facile à gérer, mais je veux vous faire travailler les dictionnaires et leur lien avec pandas...

In [13]:
donnees = {
    "titre": [],
    "categorie": [],
    "dates_heures": [],
    "reservation": []
}


for evenement in evenements:



    titre = evenement.find("h3", class_="card-event__title")
    titre_texte = titre.text


    categorie = evenement.find("span", class_="tag-pill")
    categorie_texte = categorie.text




    lien = evenement.find("a", class_="card-event__overlay-link")
    url_evenement = lien.get("href")



    dates_heures = []
    reservation = "Réservation impossible"




    if url_evenement is not None:

        response = httpx.get(url_evenement)

        soup_evenement = BeautifulSoup(response.text, "lxml")



        sessions = soup_evenement.find_all(
            "li",
            class_="bl-he__session"
        )

        for session in sessions:

            date = session.find(
                "span",
                class_="bl-he__session-date"
            )

            heure = session.find(
                "span",
                class_="bl-he__session-time"
            )

            if date is None:
                date_texte = None
            else:
                date_texte = date.text

            if heure is None:
                heure_texte = None
            else:
                heure_texte = heure.text


            if date_texte is not None and heure_texte is not None:

                date_heure = date_texte + " - " + heure_texte

                dates_heures.append(date_heure)




        lien_reservation = soup_evenement.find(
            "a",
            class_="modal-booking__cta"
        )

        if lien_reservation is not None:
            reservation = lien_reservation.get("href")


    donnees["titre"].append(titre_texte)

    donnees["categorie"].append(categorie_texte)

    donnees["dates_heures"].append(dates_heures)

    donnees["reservation"].append(reservation)

In [14]:
compteur = 1

for i in range(5):

    print(f"Événement {compteur} : {donnees['titre'][i]} - {donnees['categorie'][i]}")

    for date_heure in donnees["dates_heures"][i]:
        print(f"   Le {date_heure}")

    print(f"   Réservation : {donnees['reservation'][i]}")

    compteur = compteur + 1

Événement 1 : DEVIN TOWNSEND - Concert
   Le mercredi 23 septembre 2026 - 20h00
   Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/911/le_cepac_silo/devin_townsend
Événement 2 : The bootleg beatles - Concert
   Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/890/le_cepac_silo/the_bootleg_beatles
Événement 3 : LAURENT FEBVAY - One man show
   Le samedi 26 septembre 2026 - 20h30
   Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/665/le_cepac_silo/laurent_febvay
Événement 4 : LETZ ZEP - Concert
   Le mercredi 30 septembre 2026 - 20h00
   Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/911/le_cepac_silo/devin_townsend
Événement 5 : THE SISTERS OF MERCY - Concert
   Le jeudi 01 octobre 2026 - 20h00
   Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/845/le_cepac_silo/the_sisters_of_mercy

In [17]:
# print first event where: reservation = "Réservation impossible"
assumption = False
i=1
while assumption == False and i < len(donnees['reservation']):
    if donnees['reservation'][i] == "Réservation impossible":
        print(f"Événement: {donnees['titre'][i]} - {donnees['categorie'][i]}, Réservation: {donnees['reservation'][i]}")
        assumption = True
    i += 1

Événement: DRAG RACE FRANCE LIVE - Comédie musicale, Réservation: Réservation impossible

#### Q13

## <font color='red'> Point de validation 4 : une fois que vous aurez terminé cette question, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 


Récupérer, dans le même dictionnaire python, le prix de chaque place. Il existe généralement plusieurs catégories réservables mais, selon les événements / salles, toutes les catégories ne sont pas forcément réservables. 
    
Pour chaque événement, vous récupérerez donc les prix - par ordre de priorité - de la "catégorie 2", puis de la "catégorie assis- placement libre", puis de la "catégorie unique", ou bien enfin de la "fosse". 
Si plusieurs prix sont possibles pour la catégorie que vous avez sélectionnée, alors prenez le prix minimum.

Lorsque la catégorie existe mais que vous ne pouvez pas accéder au prix car le concert est complet, remplacez le prix par None (puisque vous ne pouvez pas le connaître a priori).

Attention : vous devez gérer automatiquement les redirections de pages, quand c'est le cas.

In [18]:
##Je me suis permis de changer un peu les categories car dans le site il y categorie 1,2 ou OR mais pas fosse ou categorie unique

import httpx
from bs4 import BeautifulSoup


donnees = {
    "titre": [],
    "categorie": [],
    "dates_heures": [],
    "reservation": [],
    "categorie_2": [],
    "prix_categorie_2": [],
    "categorie_1": [],
    "prix_categorie_1": [],
    "categorie_or": [],
    "prix_categorie_or": []
}


for evenement in evenements:

    titre = evenement.find(
        "h3",
        class_="card-event__title"
    )

    if titre is None:
        titre_texte = None
    else:
        titre_texte = titre.text.strip()


    categorie = evenement.find(
        "span",
        class_="tag-pill"
    )

    if categorie is None:
        categorie_texte = None
    else:
        categorie_texte = categorie.text.strip()


    lien = evenement.find(
        "a",
        class_="card-event__overlay-link"
    )

    if lien is None:
        url_evenement = None
    else:
        url_evenement = lien.get("href")


    dates_heures = []

    reservation = "Réservation impossible"

    categorie_2 = None
    prix_categorie_2 = None

    categorie_1 = None
    prix_categorie_1 = None

    categorie_or = None
    prix_categorie_or = None


    if url_evenement is not None:

        response = httpx.get(
            url_evenement,
            follow_redirects=True
        )

        soup_evenement = BeautifulSoup(
            response.text,
            "lxml"
        )


        sessions = soup_evenement.find_all(
            "li",
            class_="bl-he__session"
        )

        for session in sessions:

            date = session.find(
                "span",
                class_="bl-he__session-date"
            )

            heure = session.find(
                "span",
                class_="bl-he__session-time"
            )

            if date is None:
                date_texte = None
            else:
                date_texte = date.text.strip()

            if heure is None:
                heure_texte = None
            else:
                heure_texte = heure.text.strip()

            if date_texte is not None and heure_texte is not None:

                date_heure = (
                    date_texte
                    + " - "
                    + heure_texte
                )

                dates_heures.append(
                    date_heure
                )


        lien_reservation = soup_evenement.find(
            "a",
            class_="modal-booking__cta"
        )

        if lien_reservation is not None:

            reservation = lien_reservation.get("href")


            response_reservation = httpx.get(
                reservation,
                follow_redirects=True
            )

            soup_reservation = BeautifulSoup(
                response_reservation.text,
                "lxml"
            )


            categories_places = soup_reservation.find_all(
                "div",
                class_="category-wrapper"
            )


            for categorie_place in categories_places:

                titre_place = categorie_place.find(
                    "div",
                    class_="title"
                )

                if titre_place is not None:

                    texte_categorie = titre_place.text.strip()
                    texte_categorie_min = texte_categorie.lower()


                    prix_balises = categorie_place.find_all(
                        "div",
                        class_="category-price"
                    )

                    prix_trouves = []


                    for prix_balise in prix_balises:

                        prix_texte = prix_balise.text.strip()

                        prix_texte = prix_texte.replace(
                            "€",
                            ""
                        )

                        prix_texte = prix_texte.replace(
                            "\xa0",
                            ""
                        )

                        prix_texte = prix_texte.replace(
                            ",",
                            "."
                        )

                        prix_texte = prix_texte.strip()


                        try:

                            prix_nombre = float(
                                prix_texte
                            )

                            prix_trouves.append(
                                prix_nombre
                            )

                        except:

                            pass


                    if len(prix_trouves) > 0:

                        prix_minimum = min(
                            prix_trouves
                        )

                    else:

                        prix_minimum = None



                    if "categorie 2" in texte_categorie_min:

                        categorie_2 = texte_categorie
                        prix_categorie_2 = prix_minimum


                    if "categorie 1" in texte_categorie_min:

                        categorie_1 = texte_categorie
                        prix_categorie_1 = prix_minimum


                    if "categorie or" in texte_categorie_min:

                        categorie_or = texte_categorie
                        prix_categorie_or = prix_minimum


    donnees["titre"].append(
        titre_texte
    )

    donnees["categorie"].append(
        categorie_texte
    )

    donnees["dates_heures"].append(
        dates_heures
    )

    donnees["reservation"].append(
        reservation
    )

    donnees["categorie_2"].append(
        categorie_2
    )

    donnees["prix_categorie_2"].append(
        prix_categorie_2
    )

    donnees["categorie_1"].append(
        categorie_1
    )

    donnees["prix_categorie_1"].append(
        prix_categorie_1
    )

    donnees["categorie_or"].append(
        categorie_or
    )

    donnees["prix_categorie_or"].append(
        prix_categorie_or
    )

In [19]:
compteur = 1

for i in range(len(donnees["titre"])):

    print(
        f"Événement {compteur} : "
        f"{donnees['titre'][i]}"
    )

    print(
        "Catégorie de l'événement :",
        donnees["categorie"][i]
    )


    for date_heure in donnees["dates_heures"][i]:

        print(
            "   Le",
            date_heure
        )


    print(
        "Réservation :",
        donnees["reservation"][i]
    )


    print(
        "Catégorie 2 :",
        donnees["categorie_2"][i]
    )

    print(
        "Prix catégorie 2 :",
        donnees["prix_categorie_2"][i]
    )


    print(
        "Catégorie 1 :",
        donnees["categorie_1"][i]
    )

    print(
        "Prix catégorie 1 :",
        donnees["prix_categorie_1"][i]
    )


    print(
        "Catégorie OR :",
        donnees["categorie_or"][i]
    )

    print(
        "Prix catégorie OR :",
        donnees["prix_categorie_or"][i]
    )


    print()

    compteur = compteur + 1

Événement 1 : DEVIN TOWNSEND
Catégorie de l'événement : Concert
   Le mercredi 23 septembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/911/le_cepac_silo/devin_townsend
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 63.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 74.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 90.5

Événement 2 : The bootleg beatles
Catégorie de l'événement : Concert
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/890/le_cepac_silo/the_bootleg_beatles
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 3 : LAURENT FEBVAY
Catégorie de l'événement : One man show
   Le samedi 26 septembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/665/le_cepac_silo/laurent_febvay
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 29.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 39.0
Catégorie OR : None
Prix catégorie OR : None

Événement 4 : LETZ ZEP
Catégorie de l'événement : Concert
   Le mercredi 30 septembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/911/le_cepac_silo/devin_townsend
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 63.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 74.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 90.5

Événement 5 : THE SISTERS OF MERCY
Catégorie de l'événement : Concert
   Le jeudi 01 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/845/le_cepac_silo/the_sisters_of_mercy
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 6 : BREL !
Catégorie de l'événement : Spectacle
   Le dimanche 04 octobre 2026 - 17h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/678/le_cepac_silo/brel_le_spectacle
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.4
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 54.4
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 59.4

Événement 7 : Marie Benoliel
Catégorie de l'événement : Spectacle
   Le mercredi 07 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/972/le_cepac_silo/marie_benoliel
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 8 : TIF
Catégorie de l'événement : Concert - Rap / Urbain
   Le jeudi 08 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/947/le_cepac_silo/tif
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 9 : Boudchart
Catégorie de l'événement : Concert
   Le vendredi 09 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/1005/le_cepac_silo/boudchart_a_marseille_
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 45.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 55.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 65.0

Événement 10 : WORLDS APART
Catégorie de l'événement : Concert
   Le samedi 10 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/797/le_cepac_silo/worlds_apart
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 49.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 59.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 11 : Amine Radi
Catégorie de l'événement : Humour
   Le samedi 17 octobre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/822/le_cepac_silo/amine_radi
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 35.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 12 : TINA ARENA
Catégorie de l'événement : Concert
   Le mercredi 21 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/605/le_cepac_silo/tina_arena
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 49.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 59.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 69.0

Événement 13 : THE VOICE OF GEORGE MICHAEL
Catégorie de l'événement : Concert
   Le jeudi 12 février 2026 - 20h30
   Le jeudi 22 octobre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/751/
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 14 : Naïm
Catégorie de l'événement : Humour
   Le samedi 24 octobre 2026 - 20h00
   Le samedi 20 mars 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/608/le_cepac_silo/naim_chapitre_iii
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 35.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 40.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 15 : Samuel Bambi
Catégorie de l'événement : Humour
   Le jeudi 29 octobre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/823/le_cepac_silo/samuel_bambi
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 31.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 36.0
Catégorie OR : None
Prix catégorie OR : None

Événement 16 : Bachar Mar-Khalifé joue Christophe
Catégorie de l'événement : Concert
   Le vendredi 30 octobre 2026 - 21h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/978/le_cepac_silo/bachar_mar_khalife_joue_christophe
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 17 : Belinda Davids
Catégorie de l'événement : Concert
   Le mercredi 04 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/740/le_cepac_silo/belinda_davids
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 85.0

Événement 18 : THE 5 ROSIES – TRIBUTE TO AC/DC
Catégorie de l'événement : Concert
   Le jeudi 05 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/828/le_cepac_silo/the_5_rosies_tribute_to_ac_dc
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 55.0

Événement 19 : NACIM HADDAD
Catégorie de l'événement : Concert
   Le samedi 07 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/1016/le_cepac_silo/nacim_haddad
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 47.6
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 56.6
Catégorie OR : None
Prix catégorie OR : None

Événement 20 : Hubert-Félix Thiéfaine
Catégorie de l'événement : Concert
   Le dimanche 08 novembre 2026 - 18h00
   Le samedi 06 mars 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/881/le_cepac_silo/hubert_felix_thiefaine
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 52.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 62.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 72.0

Événement 21 : SECRET(S) MEDICAL
Catégorie de l'événement : Théâtre
   Le jeudi 12 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/856/le_cepac_silo/secret_s_medical
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 35.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 56.5
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 69.8

Événement 22 : SO LA LUNE
Catégorie de l'événement : Concert - Rap / Urbain
   Le vendredi 13 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/859/le_cepac_silo/so_la_lune
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 37.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 39.0
Catégorie OR : None
Prix catégorie OR : None

Événement 23 : DRAG RACE FRANCE LIVE
Catégorie de l'événement : Comédie musicale
   Le samedi 14 novembre 2026 - 20h00
Réservation : Réservation impossible
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 24 : MARY CANDIES
Catégorie de l'événement : Jeune Public
   Le dimanche 15 novembre 2026 - 15h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/870/le_cepac_silo/mary_candies
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 25 : Tutu
Catégorie de l'événement : Danse
   Le jeudi 19 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/668/le_cepac_silo/tutu
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 51.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 61.0
Catégorie OR : None
Prix catégorie OR : None

Événement 26 : Danse avec les stars
Catégorie de l'événement : Danse
   Le vendredi 20 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/864/le_cepac_silo/danse_avec_les_stars_2026
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 27 : Kad Merad & Michèle Laroque
Catégorie de l'événement : Humour
   Le samedi 21 novembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/634/le_cepac_silo/michele_laroque_et_kad_merad
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 28 : SPIDER-MAN
Catégorie de l'événement : Spectacle
   Le dimanche 22 novembre 2026 - 17h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/544/le_cepac_silo/spiderman_en_cine_concert
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 49.9
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 69.9
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 79.9

Événement 29 : LAURENT VOULZY
Catégorie de l'événement : Concert
   Le mercredi 25 novembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/965/le_cepac_silo/laurent_voulzy
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 49.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 59.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 65.0

Événement 30 : Souad Massi
Catégorie de l'événement : Concert
   Le jeudi 26 novembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/817/le_cepac_silo/souad_massi
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 55.0

Événement 31 : TITOFF
Catégorie de l'événement : One man show
   Le samedi 28 novembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/695/le_cepac_silo/titoff
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 36.2
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 41.2
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 46.2

Événement 32 : CASSE-NOISETTE – BRITISH FESTIVAL BALLET
Catégorie de l'événement : Ballet
   Le dimanche 29 novembre 2026 - 13h30
   Le dimanche 29 novembre 2026 - 17h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/765/le_cepac_silo/casse_noisette
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 65.0

Événement 33 : Jamel Comedy Club
Catégorie de l'événement : Humour
   Le mercredi 02 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/927/le_cepac_silo/jamel_comedy_club
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 36.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 40.0
Catégorie OR : None
Prix catégorie OR : None

Événement 34 : MADAME ARTHUR ENSORCELLE DISNEY
Catégorie de l'événement : Spectacle
   Le jeudi 03 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/940/le_cepac_silo/madame_arthur_ensorcelle_disney
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 25.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 35.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 42.0

Événement 35 : Ronja  – Vincent Peirani
Catégorie de l'événement : Jeune Public
   Le vendredi 04 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/897/le_cepac_silo/ronja_vincent_peirani
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 36 : Lynda Lemay et Jean-Felix Lalanne
Catégorie de l'événement : Concert
   Le mardi 08 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/768/le_cepac_silo/lynda_lemay_et_jean_felix_lalanne
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 50.5
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 61.5
Catégorie OR : None
Prix catégorie OR : None

Événement 37 : LALOU
Catégorie de l'événement : Humour
   Le mercredi 09 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/849/le_cepac_silo/lalou_qui_n_a_pas_de_nom_de_spectacle
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 32.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 36.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 39.0

Événement 38 : DAVID CASTELLO-LOPES
Catégorie de l'événement : Humour
   Le jeudi 10 décembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/810/le_cepac_silo/david_castello_lopes
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 45.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 52.0

Événement 39 : PIETRAGALLA BARBARA
Catégorie de l'événement : Danse
   Le vendredi 11 décembre 2026 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/762/le_cepac_silo/pietragalla_barbara
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 40 : Légendes Arabes
Catégorie de l'événement : Spectacle
   Le samedi 12 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/873/le_cepac_silo/legendes_arabes
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 45.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 55.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 41 : UN SOIR AVEC PIERRE ARDITI
Catégorie de l'événement : Théâtre
   Le lundi 14 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/876/le_cepac_silo/un_soir_avec_pierre_arditi
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 47.0
Catégorie OR : None
Prix catégorie OR : None

Événement 42 : HIBA TAWAJI INVITE IBRAHIM MAALOUF
Catégorie de l'événement : Concert
   Le mardi 15 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/770/le_cepac_silo/hiba_tawaji_invite_ibrahim_maalouf
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 56.5
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 69.5
Catégorie OR : None
Prix catégorie OR : None

Événement 43 : Benjamin Biolay
Catégorie de l'événement : Concert
   Le mercredi 16 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/818/le_cepac_silo/benjamin_biolay
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 51.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 56.5
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 67.5

Événement 44 : Laurent Gerra
Catégorie de l'événement : Humour
   Le samedi 19 décembre 2026 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/819/le_cepac_silo/laurent_gerra
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 59.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 69.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 75.0

Événement 45 : LE LAC DES CYGNES – IMPERIAL HERITAGE BALLET
Catégorie de l'événement : Ballet
   Le lundi 04 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/914/le_cepac_silo/le_lac_des_cygnes
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : CATEGORIE OR
Prix catégorie OR : None

Événement 46 : Verino
Catégorie de l'événement : Humour
   Le vendredi 08 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/962/le_cepac_silo/verino
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.2
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 44.2
Catégorie OR : None
Prix catégorie OR : None

Événement 47 : MARIZA
Catégorie de l'événement : Concert
   Le samedi 09 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/900/le_cepac_silo/mariza
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 45.5
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 67.5
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 78.5

Événement 48 : LA RUE KETANOU
Catégorie de l'événement : Concert
   Le mercredi 13 janvier 2027 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/959/le_cepac_silo/la_rue_ketanou
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 49 : Sellig
Catégorie de l'événement : Humour
   Le jeudi 14 janvier 2027 - 20h30
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/918/le_cepac_silo/sellig_episode_7_
Catégorie 2 : None
Prix catégorie 2 : None
Catégorie 1 : None
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 50 : Anne Tuffigo
Catégorie de l'événement : Spectacle
   Le samedi 16 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/974/le_cepac_silo/anne_tuffigo
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 44.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 49.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 59.0

Événement 51 : LES QUATRE SAISONS
Catégorie de l'événement : Ballet
   Le vendredi 22 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/830/le_cepac_silo/les_4_saisons_ballet
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 46.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 56.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 68.0

Événement 52 : ILYES DJADEL
Catégorie de l'événement : Humour
   Le samedi 23 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/889/le_cepac_silo/ilyes_djadel
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 45.0
Catégorie OR : None
Prix catégorie OR : None

Événement 53 : MANO FAIT SON SHOW
Catégorie de l'événement : Spectacle
   Le mercredi 27 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/993/le_cepac_silo/mano_fait_son_show
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 49.0
Catégorie OR : CATEGORIE OR
Prix catégorie OR : 59.0

Événement 54 : Edgar-Yves
Catégorie de l'événement : Humour
   Le jeudi 28 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/773/le_cepac_silo/edgar_yves_jr._
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : None
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : None
Catégorie OR : None
Prix catégorie OR : None

Événement 55 : MOGUIZ
Catégorie de l'événement : Humour
   Le samedi 30 janvier 2027 - 20h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/835/le_cepac_silo/moguiz
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 36.0
Catégorie 1 : CATEGORIE 1
Prix catégorie 1 : 39.5
Catégorie OR : None
Prix catégorie OR : None

Événement 56 : JEREMY HABABOU
Catégorie de l'événement : Concert
   Le dimanche 31 janvier 2027 - 17h00
Réservation : https://billetterie.cepacsilo-marseille.fr/fr/product/833/le_cepac_silo/jeremy_hababou
Catégorie 2 : CATEGORIE 2
Prix catégorie 2 : 39.0

#### Q14
On veut maintenant mettre toutes ces informations dans un dataframe de la librairie pandas nommé "evenements": https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

Pour ceux qui ne connaîtraient toujours pas la librairie pandas, elle nous permet de présenter des données de manière facilement lisible, et de calculer des statistiques basiques sur ces données.

Une fois tous les champs bien vérifiés, vous pouvez supprimer les colonnes concernant le numéro de l'événement, les dates "complètes" (mais pas les noms de jours etc), et les liens de réservation.

La sortie attendue est du type :

N.B. Si on avait utilisé une liste au lieu d'un dictionnaire, on aurait a priori obtenu une seule colonne pour "Prix" par exemple (donc moins de NaN), mais vous auriez plusieurs lignes pour un même "titre" (souvent, l'artiste)... Ici, il y a au plus 3 dates pour chaque "titre", donc les deux solutions restent acceptables.

<img src="Capture d’écran 2026-07-24 à 15.00.29.png">

In [20]:
import pandas as pd


evenements = pd.DataFrame(donnees)


evenements["jour_1"] = None
evenements["heure_1"] = None

evenements["jour_2"] = None
evenements["heure_2"] = None

evenements["jour_3"] = None
evenements["heure_3"] = None


for i in range(len(evenements)):

    dates = evenements.loc[i, "dates_heures"]


    if len(dates) >= 1:

        morceaux = dates[0].split(" - ")

        date = morceaux[0]
        heure = morceaux[1]

        jour = date.split()[0]

        evenements.loc[i, "jour_1"] = jour
        evenements.loc[i, "heure_1"] = heure


    if len(dates) >= 2:

        morceaux = dates[1].split(" - ")

        date = morceaux[0]
        heure = morceaux[1]

        jour = date.split()[0]

        evenements.loc[i, "jour_2"] = jour
        evenements.loc[i, "heure_2"] = heure


    if len(dates) >= 3:

        morceaux = dates[2].split(" - ")

        date = morceaux[0]
        heure = morceaux[1]

        jour = date.split()[0]

        evenements.loc[i, "jour_3"] = jour
        evenements.loc[i, "heure_3"] = heure


evenements = evenements.drop(
    columns=[
        "dates_heures",
        "reservation"
    ]
)


display(evenements)

,titre,categorie,categorie_2,prix_categorie_2,categorie_1,prix_categorie_1,categorie_or,prix_categorie_or,jour_1,heure_1,jour_2,heure_2,jour_3,heure_3
0,DEVIN TOWNSEND,Concert,CATEGORIE 2,63.0,CATEGORIE 1,74.0,CATEGORIE OR,90.5,mercredi,20h00,None,None,None,None
1,The bootleg beatles,Concert,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None
2,LAURENT FEBVAY,One man show,CATEGORIE 2,29.0,CATEGORIE 1,39.0,NaN,NaN,samedi,20h30,None,None,None,None
3,LETZ ZEP,Concert,CATEGORIE 2,63.0,CATEGORIE 1,74.0,CATEGORIE OR,90.5,mercredi,20h00,None,None,None,None
4,THE SISTERS OF MERCY,Concert,NaN,NaN,NaN,NaN,NaN,NaN,jeudi,20h00,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,BLANDINE LEHOUT,Humour,CATEGORIE 2,36.0,CATEGORIE 1,39.0,NaN,NaN,vendredi,20h00,None,None,None,None
106,SOFIA BELABBES,Humour,CATEGORIE 2,32.0,CATEGORIE 1,35.0,NaN,NaN,vendredi,20h00,None,None,None,None
107,LES DIX COMMANDEMENTS,Spectacle,CATEGORIE 2,49.0,CATEGORIE 1,64.0,CATEGORIE OR,74.0,jeudi,20h30,None,None,None,None
108,YANN MARGUET,Humour,CATEGORIE 2,36.0,CATEGORIE 1,39.0,NaN,NaN,samedi,20h00,None,None,None,None
109,PIAF ! LE SPECTACLE,Spectacle,CATEGORIE 2,54.4,CATEGORIE 1,59.4,CATEGORIE OR,69.4,mardi,20h30,None,None,None,None

#### Q15

## <font color='red'> Point de validation 5 : une fois que vous aurez terminé cette question et vérifié avec le répertoire cepac_silo_pages donné sur Ametice que vous obtenez la bonne réponse, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 

Mettre tous les concerts du dataframe "evenement" dans un dataframe "concert".
Mettre tous les spectacles humour ou one-man-show du dataframe "evenement" dans un dataframe "comedie".

Pour répondre aux questions suivantes, utilisez les fonctions pandas nécessaires. Ne pas chercher les réponses à ces questions à la main, ni en utilisant une IA de quelque façon que ce soit...

Parmi les événements mentionnés dans cette page, combien y a-t-il de concerts ? Combien de "comédies" ?

(Si vous utilisez le répertoire cepac_silo_pages, vous devriez trouver respectivement 40 et 29).

#### Q16

Combien d\'événements / dates pour lesquels le prix n\'est pas mentionné ? 

(Exceptionnellement, vous pouvez répondre à la question juste avec un affichage, pas besoin d'écrire une fonction pour retrouver cela).

In [21]:
concert = evenements[
    evenements["categorie"].str.contains(
        "Concert",
        case=False,
        na=False
    )
]


comedie = evenements[
    evenements["categorie"].str.contains(
        "Humour|One man show|One-man-show",
        case=False,
        na=False
    )
]

In [22]:
display(concert)

,titre,categorie,categorie_2,prix_categorie_2,categorie_1,prix_categorie_1,categorie_or,prix_categorie_or,jour_1,heure_1,jour_2,heure_2,jour_3,heure_3
0,DEVIN TOWNSEND,Concert,CATEGORIE 2,63.0,CATEGORIE 1,74.0,CATEGORIE OR,90.5,mercredi,20h00,None,None,None,None
1,The bootleg beatles,Concert,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None
3,LETZ ZEP,Concert,CATEGORIE 2,63.0,CATEGORIE 1,74.0,CATEGORIE OR,90.5,mercredi,20h00,None,None,None,None
4,THE SISTERS OF MERCY,Concert,NaN,NaN,NaN,NaN,NaN,NaN,jeudi,20h00,None,None,None,None
7,TIF,Concert - Rap / Urbain,NaN,NaN,NaN,NaN,NaN,NaN,jeudi,20h00,None,None,None,None
8,Boudchart,Concert,CATEGORIE 2,45.0,CATEGORIE 1,55.0,CATEGORIE OR,65.0,vendredi,20h00,None,None,None,None
9,WORLDS APART,Concert,CATEGORIE 2,49.0,CATEGORIE 1,59.0,CATEGORIE OR,NaN,samedi,20h00,None,None,None,None
11,TINA ARENA,Concert,CATEGORIE 2,49.0,CATEGORIE 1,59.0,CATEGORIE OR,69.0,mercredi,20h00,None,None,None,None
12,THE VOICE OF GEORGE MICHAEL,Concert,NaN,NaN,NaN,NaN,NaN,NaN,jeudi,20h30,jeudi,20h30,None,None
15,Bachar Mar-Khalifé joue Christophe,Concert,NaN,NaN,NaN,NaN,NaN,NaN,vendredi,21h00,None,None,None,None
16,Belinda Davids,Concert,CATEGORIE 2,NaN,CATEGORIE 1,NaN,CATEGORIE OR,85.0,mercredi,20h00,None,None,None,None
17,THE 5 ROSIES – TRIBUTE TO AC/DC,Concert,CATEGORIE 2,NaN,CATEGORIE 1,NaN,CATEGORIE OR,55.0,jeudi,20h00,None,None,None,None
18,NACIM HADDAD,Concert,CATEGORIE 2,47.6,CATEGORIE 1,56.6,NaN,NaN,samedi,20h00,None,None,None,None
19,Hubert-Félix Thiéfaine,Concert,CATEGORIE 2,52.0,CATEGORIE 1,62.0,CATEGORIE OR,72.0,dimanche,18h00,samedi,20h00,None,None
21,SO LA LUNE,Concert - Rap / Urbain,CATEGORIE 2,37.0,CATEGORIE 1,39.0,NaN,NaN,vendredi,20h00,None,None,None,None
28,LAURENT VOULZY,Concert,CATEGORIE 2,49.0,CATEGORIE 1,59.0,CATEGORIE OR,65.0,mercredi,20h30,None,None,None,None
29,Souad Massi,Concert,CATEGORIE 2,NaN,CATEGORIE 1,NaN,CATEGORIE OR,55.0,jeudi,20h30,None,None,None,None
35,Lynda Lemay et Jean-Felix Lalanne,Concert,CATEGORIE 2,50.5,CATEGORIE 1,61.5,NaN,NaN,mardi,20h00,None,None,None,None
41,HIBA TAWAJI INVITE IBRAHIM MAALOUF,Concert,CATEGORIE 2,56.5,CATEGORIE 1,69.5,NaN,NaN,mardi,20h00,None,None,None,None
42,Benjamin Biolay,Concert,CATEGORIE 2,51.0,CATEGORIE 1,56.5,CATEGORIE OR,67.5,mercredi,20h00,None,None,None,None
46,MARIZA,Concert,CATEGORIE 2,45.5,CATEGORIE 1,67.5,CATEGORIE OR,78.5,samedi,20h00,None,None,None,None
47,LA RUE KETANOU,Concert,NaN,NaN,NaN,NaN,NaN,NaN,mercredi,20h30,None,None,None,None
55,JEREMY HABABOU,Concert,CATEGORIE 2,39.0,CATEGORIE 1,42.0,NaN,NaN,dimanche,17h00,None,None,None,None
65,Pomme,Concert,CATEGORIE 2,63.0,CATEGORIE 1,74.0,CATEGORIE OR,90.5,samedi,20h00,None,None,None,None
66,Thylacine,Concert,CATEGORIE 2,44.0,CATEGORIE 1,49.0,NaN,NaN,jeudi,20h00,None,None,None,None
71,The world of Queen,Concert,CATEGORIE 2,NaN,CATEGORIE 1,NaN,CATEGORIE OR,54.0,vendredi,20h30,None,None,None,None
72,Izia,Concert,CATEGORIE 2,38.4,CATEGORIE 1,45.4,NaN,NaN,samedi,20h00,None,None,None,None
73,MARGUERITE,Concert,CATEGORIE 2,31.2,CATEGORIE 1,35.2,NaN,NaN,mardi,20h00,None,None,None,None
74,The U2 Experience,Concert,CATEGORIE 2,42.0,CATEGORIE 1,49.0,CATEGORIE OR,58.0,mercredi,20h00,None,None,None,None
75,ABBA GOLD – The concert show,Concert,CATEGORIE 2,49.2,CATEGORIE 1,57.2,CATEGORIE OR,65.2,jeudi,20h00,None,None,None,None
79,PIERRE DE MAERE,Concert,CATEGORIE 2,36.2,CATEGORIE 1,39.6,NaN,NaN,mercredi,20h00,None,None,None,None
80,Sniper,Concert - Rap / Urbain,CATEGORIE 2,36.0,CATEGORIE 1,42.0,NaN,NaN,jeudi,20h30,None,None,None,None
81,AMBRE,Concert,CATEGORIE 2,45.0,CATEGORIE 1,55.0,CATEGORIE OR,65.0,vendredi,20h00,None,None,None,None
83,Sheryfa Luna,Concert,CATEGORIE 2,45.0,CATEGORIE 1,52.0,NaN,NaN,dimanche,17h00,None,None,None,None
84,RODRIGO Y GABRIELA,Concert,CATEGORIE 2,44.0,CATEGORIE 1,49.0,NaN,NaN,jeudi,20h00,None,None,None,None
85,Camille,Concert,CATEGORIE 2,44.2,CATEGORIE 1,49.2,CATEGORIE OR,59.8,vendredi,20h00,None,None,None,None
87,Yanns,Concert,CATEGORIE 2,41.4,CATEGORIE 1,49.4,NaN,NaN,dimanche,18h00,None,None,None,None
91,The Muse Experience,Concert,CATEGORIE 2,34.0,CATEGORIE 1,39.0,NaN,NaN,jeudi,20h30,None,None,None,None
93,NIGHT FEVER : A TRIBUTE TO THE BEE GEES,Concert,CATEGORIE 2,49.0,CATEGORIE 1,59.0,CATEGORIE OR,69.0,jeudi,20h00,None,None,None,None
94,Gilbert Montagné,Concert,CATEGORIE 2,45.0,CATEGORIE 1,57.0,CATEGORIE OR,69.0,samedi,20h00,None,None,None,None
95,Hervé Vilard,Concert,CATEGORIE 2,39.0,CATEGORIE 1,49.0,CATEGORIE OR,59.0,dimanche,17h00,None,None,None,None
99,"COVERTRAMP, HOMMAGE A SUPERTRAMP",Concert,CATEGORIE 2,49.0,CATEGORIE 1,59.0,CATEGORIE OR,69.0,samedi,20h00,None,None,None,None
100,Ycare,Concert,CATEGORIE 2,36.0,CATEGORIE 1,40.0,NaN,NaN,vendredi,20h00,None,None,None,None

In [26]:
print(len(concert))

43

In [ ]:
display(comedie)

In [27]:
print(len(comedie))

33

In [24]:
sans_prix = evenements[
    evenements["prix_categorie_2"].isna()
    & evenements["prix_categorie_1"].isna()
    & evenements["prix_categorie_or"].isna()
]

display(len(sans_prix))

22

#### Q17
Parmi les événements mentionnés sur la page, quel est le jour de la semaine le plus fréquent (ne pas le chercher à la main, utiliser des fonctions pandas pour retrouver cette valeur)?

In [25]:
jours = pd.concat([
    evenements["jour_1"],
    evenements["jour_2"],
    evenements["jour_3"]
])

frequence_jours = jours.value_counts()

jour_plus_frequent = frequence_jours.idxmax()

print(
    "Le jour de la semaine le plus fréquent est :",
    jour_plus_frequent
)

Le jour de la semaine le plus fréquent est : samedi

#### Q18
On recherche maintenant les prix moyens des événements. 

On ignorera les prix à None. C'est-à-dire qu'on les mettra à nan de manière à ce qu'elles ne soient pas prises en compte dans le calcul de la moyenne...

Quel est le prix moyen d'une place pour un concert (ne pas le chercher à la main, utiliser des fonctions pandas voire numpy pour retrouver cette valeur) ? 

Quel est le prix moyen d'une place pour une comédie (ne pas le chercher à la main, utiliser des fonctions pandas voire numpy pour retrouver cette valeur) ?

In [28]:
import numpy as np


concert = concert.replace({None: np.nan})
comedie = comedie.replace({None: np.nan})


colonnes_prix = [
    "prix_categorie_2",
    "prix_categorie_1",
    "prix_categorie_or"
]


prix_moyen_concert = concert[colonnes_prix].stack().mean()


prix_moyen_comedie = comedie[colonnes_prix].stack().mean()


print(
    "Prix moyen d'une place pour un concert :",
    prix_moyen_concert,
    "€"
)

print(
    "Prix moyen d'une place pour une comédie :",
    prix_moyen_comedie,
    "€"
)

Prix moyen d'une place pour un concert : 54.526436781609185 €
Prix moyen d'une place pour une comédie : 40.74833333333333 €

#### Q19

## <font color='red'> Point de validation Bonus : une fois que vous aurez terminé cette question, appelez la prof et attendez-vous à répondre à des questions sur votre code <img src="buttonValidate.gif"> 
    
Menez à bien une analyse exploratoire de ces données, et une visualisation de ces données, qui soit la plus intéressante possible. Vous êtes libres du choix des librairies, mais vous devrez être capables d'expliquer, ligne par ligne, votre code...